import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function toVal(v: string | undefined): string | undefined {
    return v === '-' || v === undefined ? undefined : v;
}

const plants: Array<{
    scientificName: string;
    commonNameAr: string;
    commonNameEn?: string;
    localNames: string[];
    synonyms: string[];
    plantType: 'TREE' | 'SHRUB' | 'HERB' | 'CROP' | 'WILDFLOWER';
    family?: string;
    descriptionAr?: string;
    heightMinMeters?: number;
    heightMaxMeters?: number;
    beekeepingValue: Record<string, unknown>;
    flowering: Record<string, unknown>;
    environment: Record<string, unknown>;
    nativeRegions: string[];
    cultivatedRegions: string[];
}> = [
    // ===== الأشجار (Trees) =====
    {
        scientificName: 'Ziziphus spina-christi',
        commonNameAr: 'السدر (النبق)',
        commonNameEn: "Christ's thorn / Sidr",
        localNames: ['النبق', 'السدر البري', 'الزفزوف'],
        synonyms: ['Ziziphus vulgaris'],
        plantType: 'TREE',
        family: 'Rhamnaceae',
        descriptionAr: 'شجرة معمرة دائمة الخضرة، تنتشر في الأودية والسهول، تنتج أجود أنواع العسل في المملكة.',
        heightMinMeters: 3,
        heightMaxMeters: 15,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 5 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'المصدر الأول للعسل في المملكة' },
        flowering: { startMonth: 7, endMonth: 10, peakMonth: 8, flowerColor: 'أصفر مخضر', nectarTiming: 'ALL_DAY', notes: 'يزهر مرتين في السنة في بعض المناطق' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Vachellia gerrardii',
        commonNameAr: 'الطلح',
        commonNameEn: 'Red acacia',
        localNames: ['الطلح النجدي', 'طلح'],
        synonyms: ['Acacia gerrardii'],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'شجرة كبيرة من أشجار العسل الشهيرة، تنتشر في وسط وجنوب المملكة.',
        heightMinMeters: 4,
        heightMaxMeters: 12,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل الطلح من أشهر الأعسال السعودية' },
        flowering: { startMonth: 5, endMonth: 8, peakMonth: 6, flowerColor: 'أبيض مصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة مكة المكرمة', 'منطقة المدينة المنورة', 'منطقة نجران', 'منطقة جازان'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Vachellia tortilis',
        commonNameAr: 'السمرة (السمر)',
        commonNameEn: 'Umbrella thorn acacia',
        localNames: ['السمر', 'السمرة'],
        synonyms: ['Acacia tortilis', 'Acacia raddiana'],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'شجرة صحراوية واسعة الانتشار، غطاء نباتي ممتاز للنحل في موسم الربيع.',
        heightMinMeters: 3,
        heightMaxMeters: 10,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل السمرة من الأعسال الفاخرة' },
        flowering: { startMonth: 1, endMonth: 4, peakMonth: 3, flowerColor: 'أبيض كريمي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'HYPER_ARID'], soilType: ['SANDY', 'ROCKY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة مكة المكرمة', 'منطقة المدينة المنورة', 'المنطقة الشرقية'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Vachellia flava (ehrenbergiana)',
        commonNameAr: 'السلم',
        commonNameEn: 'Salam acacia',
        localNames: ['السلم'],
        synonyms: ['Acacia ehrenbergiana', 'Vachellia ehrenbergiana'],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'شجرة موسم تزهيرها طويل يمتد لأغلب الصيف، مصدر رحيق مهم.',
        heightMinMeters: 3,
        heightMaxMeters: 8,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 5, endMonth: 9, peakMonth: 7, flowerColor: 'أصفر ذهبي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'CLAY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل', 'المنطقة الشرقية'],
        cultivatedRegions: ['منطقة الرياض', 'منطقة القصيم'],
    },
    {
        scientificName: 'Senegalia asak',
        commonNameAr: 'السيال',
        commonNameEn: 'Asak acacia',
        localNames: ['السيال', 'السهل'],
        synonyms: ['Acacia asak'],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'شجرة منتجة للعسل الخريفي، تنتشر في المرتفعات الجنوبية الغربية.',
        heightMinMeters: 4,
        heightMaxMeters: 10,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل السيال الخريفي' },
        flowering: { startMonth: 6, endMonth: 9, peakMonth: 8, flowerColor: 'أبيض مصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'TROPICAL'], soilType: ['LOAMY', 'ROCKY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة جازان', 'منطقة الباحة', 'منطقة مكة المكرمة'],
        cultivatedRegions: ['منطقة عسير', 'منطقة جازان', 'منطقة الباحة'],
    },
    {
        scientificName: 'Astragalus spp.',
        commonNameAr: 'القتاد',
        commonNameEn: 'Milkvetch / Astragalus',
        localNames: ['القتاد', 'القطة'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'نبات رحيقي مهم، ينتشر في المناطق الجبلية، ينتج عسلاً ذهبياً فاخراً.',
        heightMinMeters: 0.5,
        heightMaxMeters: 2,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 5 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH', notes: 'عسل القتاد الذهبي من أغلى أنواع العسل' },
        flowering: { startMonth: 6, endMonth: 8, peakMonth: 7, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'ROCKY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Tamarix spp.',
        commonNameAr: 'الأثل (الطرفة)',
        commonNameEn: 'Tamarisk / Salt cedar',
        localNames: ['الطرفة', 'الأثل', 'العبل'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Tamaricaceae',
        descriptionAr: 'شجرة تتحمل الملوحة، غزيرة الرحيق وحبوب اللقاح، تنتشر في المناطق الرطبة.',
        heightMinMeters: 3,
        heightMaxMeters: 12,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 6, endMonth: 10, peakMonth: 8, flowerColor: 'وردي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SALINE', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Eucalyptus camaldulensis',
        commonNameAr: 'الكينا (الكافور)',
        commonNameEn: 'River red gum',
        localNames: ['الكافور', 'الكينا', 'شجرة الكافور'],
        synonyms: ['Eucalyptus globulus'],
        plantType: 'TREE',
        family: 'Myrtaceae',
        descriptionAr: 'شجرة سريعة النمو، مصدر رحيق متعدد المواسم، تنتج عسلاً بنكهة مميزة.',
        heightMinMeters: 15,
        heightMaxMeters: 30,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 3, endMonth: 11, peakMonth: 6, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY', notes: 'موسم تزهير طويل يمتد لأغلب السنة' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['أستراليا (مستورد)'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Phoenix dactylifera',
        commonNameAr: 'النخيل',
        commonNameEn: 'Date palm',
        localNames: ['النخلة', 'التمر'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Arecaceae',
        descriptionAr: 'شجرة مباركة، مصدر رئيسي لحبوب اللقاح في المناطق الزراعية.',
        heightMinMeters: 10,
        heightMaxMeters: 25,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'HIGH', rating: 5 }, honeydew: false, attraction: 'MEDIUM', notes: 'مصدر رئيسي لحبوب اللقاح' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أصفر', nectarTiming: 'MORNING' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Citrus spp.',
        commonNameAr: 'الحمضيات',
        commonNameEn: 'Citrus trees',
        localNames: ['البرتقال', 'الليمون', 'الجريب فروت'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Rutaceae',
        descriptionAr: 'أشجار مثمرة تنتج أزهاراً عطرية غنية بالرحيق، عسل الحمضيات فاخر.',
        heightMinMeters: 3,
        heightMaxMeters: 8,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل الحمضيات الفاخر' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جنوب شرق آسيا (مستورد)'],
        cultivatedRegions: ['منطقة القصيم', 'منطقة الرياض', 'منطقة مكة المكرمة', 'منطقة عسير', 'منطقة جازان', 'منطقة تبوك'],
    },
    {
        scientificName: 'Acacia salicina',
        commonNameAr: 'الأكاسيا (السنط)',
        commonNameEn: 'Willow acacia',
        localNames: ['السنط', 'الأكاسيا'],
        synonyms: ['Acacia salicina'],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'شجرة دائمة الخضرة، مصدر جيد للرحيق في الربيع والصيف.',
        heightMinMeters: 5,
        heightMaxMeters: 12,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 4, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر باهت', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY', 'CLAY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['أستراليا (مستورد)'],
        cultivatedRegions: ['منطقة الرياض', 'منطقة مكة المكرمة', 'المنطقة الشرقية'],
    },
    {
        scientificName: 'Acacia spp.',
        commonNameAr: 'القرض (الأكاسيا)',
        commonNameEn: 'Acacia (general)',
        localNames: ['القرض', 'القرظ'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Fabaceae',
        descriptionAr: 'مجموعة من أشجار الأكاسيا المختلفة، مصدر رحيق مهم للنحل.',
        heightMinMeters: 3,
        heightMaxMeters: 10,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 8, peakMonth: 5, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'ROCKY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Maerua crassifolia',
        commonNameAr: 'السرح',
        commonNameEn: 'Meru',
        localNames: ['السرح'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Capparaceae',
        descriptionAr: 'نبات رحيقي مهم في المناطق الصحراوية، يتحمل الجفاف.',
        heightMinMeters: 2,
        heightMaxMeters: 6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 4, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر مخضر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'HYPER_ARID'], soilType: ['SANDY', 'ROCKY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة مكة المكرمة', 'منطقة المدينة المنورة', 'منطقة نجران'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Haloxylon persicum',
        commonNameAr: 'الغضا',
        commonNameEn: 'White saxaul',
        localNames: ['الغضا'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Amaranthaceae',
        descriptionAr: 'شجرة صحراوية، تنتشر في الرمال، قيمة نحلية منخفضة.',
        heightMinMeters: 2,
        heightMaxMeters: 5,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 9, endMonth: 11, peakMonth: 10, flowerColor: 'أصفر باهت', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['HYPER_ARID', 'ARID'], soilType: ['SANDY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['المنطقة الشرقية', 'منطقة الرياض', 'منطقة حائل', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Commiphora spp.',
        commonNameAr: 'المر',
        commonNameEn: 'Myrrh',
        localNames: ['المر', 'البتول'],
        synonyms: ['Balsamodendron spp.'],
        plantType: 'TREE',
        family: 'Burseraceae',
        descriptionAr: 'شجرة طبية تنتج صمغ المر، أزهارها مصدر رحيق موسمي.',
        heightMinMeters: 2,
        heightMaxMeters: 5,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'LOW', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 4, flowerColor: 'أحمر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['ROCKY', 'SANDY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة جازان', 'منطقة عسير', 'منطقة نجران', 'منطقة مكة المكرمة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Tamarix aphylla',
        commonNameAr: 'العبل (الأثل)',
        commonNameEn: 'Athel tamarisk',
        localNames: ['العبل', 'الأثل'],
        synonyms: ['Tamarix orientalis'],
        plantType: 'TREE',
        family: 'Tamaricaceae',
        descriptionAr: 'شجرة دائمة الخضرة تتحمل الملوحة، مصدر رحيق صيفي مهم.',
        heightMinMeters: 4,
        heightMaxMeters: 15,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 5, endMonth: 9, peakMonth: 7, flowerColor: 'وردي فاتح', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SALINE', 'SANDY', 'LOAMY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Avicennia marina',
        commonNameAr: 'المانجروف (القرم)',
        commonNameEn: 'Grey mangrove',
        localNames: ['القرم', 'المانجروف', 'الشورة'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Acanthaceae',
        descriptionAr: 'شجرة ساحلية تنمو في مياه البحر، مصدر رحيق ممتاز في المناطق الساحلية.',
        heightMinMeters: 2,
        heightMaxMeters: 8,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل المانجروف المالح الفاخر' },
        flowering: { startMonth: 6, endMonth: 8, peakMonth: 7, flowerColor: 'أصفر ذهبي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['TROPICAL', 'SEMI_ARID'], soilType: ['SALINE', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'FULL_SUN' },
        nativeRegions: ['المنطقة الشرقية', 'منطقة جازان', 'منطقة مكة المكرمة'],
        cultivatedRegions: ['المنطقة الشرقية', 'منطقة جازان'],
    },
    {
        scientificName: 'Salvadora persica',
        commonNameAr: 'الأراك (المسواك)',
        commonNameEn: 'Toothbrush tree / Miswak',
        localNames: ['المسواك', 'الأراك'],
        synonyms: [],
        plantType: 'TREE',
        family: 'Salvadoraceae',
        descriptionAr: 'شجرة دائمة الخضرة، تستخدم في صناعة المساويك، أزهارها غنية بالرحيق.',
        heightMinMeters: 3,
        heightMaxMeters: 7,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أصفر مخضر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['SANDY', 'LOAMY', 'SALINE'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة جازان', 'منطقة نجران', 'منطقة مكة المكرمة', 'منطقة المدينة المنورة'],
        cultivatedRegions: ['منطقة جازان', 'منطقة مكة المكرمة'],
    },

    // ===== الشجيرات (Shrubs) =====
    {
        scientificName: 'Rhanterium epapposum',
        commonNameAr: 'العرفج',
        commonNameEn: 'Arfaj',
        localNames: ['العرفج'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Asteraceae',
        descriptionAr: 'من أهم النباتات الرحيقية الربيعية في المملكة، يغطي مساحات واسعة.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH', notes: 'من أهم النباتات الرحيقية الربيعية' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 4, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل', 'المنطقة الشرقية', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Lavandula dentata',
        commonNameAr: 'الضرم (الخزامى)',
        commonNameEn: 'Fringed lavender',
        localNames: ['الخزامى', 'الضرم'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Lamiaceae',
        descriptionAr: 'نبات عطري، مصدر رحيق ممتاز في المرتفعات، ينتج عسلاً عطرياً فاخراً.',
        heightMinMeters: 0.5,
        heightMaxMeters: 1.2,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'عسل الخزامى العطري' },
        flowering: { startMonth: 4, endMonth: 6, peakMonth: 5, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['MEDITERRANEAN', 'SEMI_ARID'], soilType: ['LOAMY', 'ROCKY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة الجوف'],
        cultivatedRegions: ['منطقة عسير', 'منطقة الباحة'],
    },
    {
        scientificName: 'Lavandula pubescens',
        commonNameAr: 'الضرم البري',
        commonNameEn: 'Downy lavender',
        localNames: ['الضرم البري', 'الخزامى البرية'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Lamiaceae',
        descriptionAr: 'نبات عطري بري، مزهر متعدد المواسم، مصدر رحيق ممتاز.',
        heightMinMeters: 0.4,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 10, endMonth: 6, peakMonth: 4, flowerColor: 'بنفسجي فاتح', nectarTiming: 'ALL_DAY', notes: 'موسم تزهير طويل يمتد من الخريف للصيف' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['ROCKY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة مكة المكرمة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Capparis spinosa',
        commonNameAr: 'الشفلح (الكبار)',
        commonNameEn: 'Caper bush',
        localNames: ['الكبار', 'الشفلح', 'الأصف'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Capparaceae',
        descriptionAr: 'شجيرة شوكية، تنتج أزهاراً جميلة غنية بالرحيق، عسل الشفلح معروف.',
        heightMinMeters: 0.5,
        heightMaxMeters: 2,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM', notes: 'عسل الشفلح' },
        flowering: { startMonth: 5, endMonth: 9, peakMonth: 7, flowerColor: 'أبيض بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['ROCKY', 'SANDY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Calotropis procera',
        commonNameAr: 'العشر (الأشخر)',
        commonNameEn: 'Sodom apple',
        localNames: ['العشر', 'الأشخر', 'العرر'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Apocynaceae',
        descriptionAr: 'شجيرة كبيرة تنمو في الأودية والسهول، أزهارها غنية بالرحيق.',
        heightMinMeters: 1.5,
        heightMaxMeters: 4,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'LOW', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 2, endMonth: 6, peakMonth: 4, flowerColor: 'أبيض بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Lycium shawii',
        commonNameAr: 'الينبوت (العوسج)',
        commonNameEn: 'Arabian boxthorn',
        localNames: ['العوسج', 'الينبوت'],
        synonyms: ['Lycium arabicum'],
        plantType: 'SHRUB',
        family: 'Solanaceae',
        descriptionAr: 'شجيرة شوكية، تزهر في الخريف والشتاء، مصدر رحيق مهم في غير المواسم.',
        heightMinMeters: 1,
        heightMaxMeters: 3,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 10, endMonth: 1, peakMonth: 11, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'ROCKY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Calligonum comosum',
        commonNameAr: 'الأرطى',
        commonNameEn: 'Arta / Calligonum',
        localNames: ['الأرطى', 'العرطى'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Polygonaceae',
        descriptionAr: 'شجيرة صحراوية تنتشر في الرمال، غطاء نباتي صحراوي واسع.',
        heightMinMeters: 0.5,
        heightMaxMeters: 2,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض وردي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['HYPER_ARID', 'ARID'], soilType: ['SANDY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['المنطقة الشرقية', 'منطقة الرياض', 'منطقة حائل', 'منطقة الجوف', 'منطقة تبوك'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Haloxylon salicornicum',
        commonNameAr: 'الرمث',
        commonNameEn: 'Ramth',
        localNames: ['الرمث'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Amaranthaceae',
        descriptionAr: 'شجيرة صحراوية ملحية، تنتشر في السباخ والمناطق الجافة.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 4, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر باهت', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'HYPER_ARID'], soilType: ['SALINE', 'SANDY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['المنطقة الشرقية', 'منطقة الرياض', 'منطقة القصيم', 'منطقة حائل'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Senna alexandrina',
        commonNameAr: 'السنا (السنامكي)',
        commonNameEn: 'Senna',
        localNames: ['السنامكي', 'السنا'],
        synonyms: ['Cassia senna', 'Cassia angustifolia'],
        plantType: 'SHRUB',
        family: 'Fabaceae',
        descriptionAr: 'نبات طبي، أزهاره مصدر رحيق متوسط القيمة.',
        heightMinMeters: 0.5,
        heightMaxMeters: 2,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة جازان', 'منطقة نجران', 'منطقة مكة المكرمة'],
        cultivatedRegions: ['منطقة جازان', 'منطقة مكة المكرمة'],
    },
    {
        scientificName: 'Artemisia herba-alba',
        commonNameAr: 'الشيح',
        commonNameEn: 'White wormwood',
        localNames: ['الشيح', 'شيح'],
        synonyms: ['Artemisia inculta'],
        plantType: 'SHRUB',
        family: 'Asteraceae',
        descriptionAr: 'نبات عطري صحراوي، قيمة نحلية منخفضة لكنه واسع الانتشار.',
        heightMinMeters: 0.3,
        heightMaxMeters: 0.8,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 9, endMonth: 11, peakMonth: 10, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY', 'ROCKY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Achillea spp.',
        commonNameAr: 'القيصوم',
        commonNameEn: 'Yarrow',
        localNames: ['القيصوم', 'حزنبل'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Asteraceae',
        descriptionAr: 'نبات عطري ربيعي، مصدر رحيق متوسط.',
        heightMinMeters: 0.3,
        heightMaxMeters: 0.8,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 4, flowerColor: 'أبيض أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'ROCKY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Salsola vermiculata',
        commonNameAr: 'الروثة',
        commonNameEn: 'Mediterranean saltwort',
        localNames: ['الروثة'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Amaranthaceae',
        descriptionAr: 'شجيرة ملحية صحراوية، قيمة نحلية منخفضة.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 5, endMonth: 7, peakMonth: 6, flowerColor: 'أخضر باهت', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'HYPER_ARID'], soilType: ['SALINE', 'SANDY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['المنطقة الشرقية', 'منطقة الرياض', 'منطقة القصيم'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Lycium europaeum',
        commonNameAr: 'العوسج (الغسول)',
        commonNameEn: 'European boxthorn',
        localNames: ['العوسج', 'الغسول'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Solanaceae',
        descriptionAr: 'شجيرة شوكية، تزهر في الربيع، مصدر رحيق متوسط.',
        heightMinMeters: 1,
        heightMaxMeters: 3,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة مكة المكرمة', 'منطقة تبوك'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Scolymus spp.',
        commonNameAr: 'الشكاعى',
        commonNameEn: 'Golden thistle',
        localNames: ['الشكاعى'],
        synonyms: [],
        plantType: 'SHRUB',
        family: 'Asteraceae',
        descriptionAr: 'نبات شوكي ربيعي، أزهاره تجذب النحل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل'],
        cultivatedRegions: [],
    },

    // ===== الأعشاب والنباتات العطرية (Herbs) =====
    {
        scientificName: 'Teucrium polium',
        commonNameAr: 'المجرى (الجعدة)',
        commonNameEn: 'Felty germander',
        localNames: ['الجعدة', 'المجرى'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Lamiaceae',
        descriptionAr: 'من أندر وأغلى أنواع العسل، نبات عطري طبي، يزهر في الصيف والخريف.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.5,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 5 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH', notes: 'من أندر وأغلى أنواع العسل السعودي' },
        flowering: { startMonth: 8, endMonth: 10, peakMonth: 9, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['ROCKY', 'LOAMY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة حائل', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Euphorbia spp.',
        commonNameAr: 'السحاء (الحلاب)',
        commonNameEn: 'Spurge',
        localNames: ['الحلاب', 'السحاء'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Euphorbiaceae',
        descriptionAr: 'من النباتات العسلية الهامة في المناطق الجبلية.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر مخضر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'TROPICAL'], soilType: ['LOAMY', 'ROCKY'], waterNeeds: 'LOW', sunExposure: 'PARTIAL_SHADE' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة جازان', 'منطقة مكة المكرمة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Not determined (Asteraceae)',
        commonNameAr: 'الطباق',
        commonNameEn: 'Not determined',
        localNames: ['الطباق'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Asteraceae',
        descriptionAr: 'نبات عشبي ربيعي، مصدر رحيق متوسط.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Not determined (Lamiaceae?)',
        commonNameAr: 'الشرم',
        commonNameEn: 'Not determined',
        localNames: ['الشرم'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Lamiaceae',
        descriptionAr: 'نبات عشبي ربيعي، مصدر رحيق متوسط.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.5,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 4, endMonth: 6, peakMonth: 5, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة القصيم', 'منطقة حائل', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Portulaca oleracea',
        commonNameAr: 'الربلة (الرجلة)',
        commonNameEn: 'Purslane',
        localNames: ['الرجلة', 'الربلة', 'البقلة'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Portulacaceae',
        descriptionAr: 'نبات عشبي صيفي، ينتشر في الحدائق والحقول.',
        heightMinMeters: 0.1,
        heightMaxMeters: 0.4,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 5, endMonth: 9, peakMonth: 7, flowerColor: 'أصفر', nectarTiming: 'MORNING' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Lavandula spp.',
        commonNameAr: 'الخزامى (اللافندر)',
        commonNameEn: 'Lavender',
        localNames: ['اللافندر', 'الخزامى'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Lamiaceae',
        descriptionAr: 'نبات عطري مشهور، مصدر رحيق ممتاز.',
        heightMinMeters: 0.4,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 4, endMonth: 7, peakMonth: 5, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['MEDITERRANEAN', 'SEMI_ARID'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك'],
        cultivatedRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة الرياض'],
    },
    {
        scientificName: 'Citrullus colocynthis',
        commonNameAr: 'الحنظل',
        commonNameEn: 'Bitter apple / Colocynth',
        localNames: ['الحنظل', 'المرارة'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Cucurbitaceae',
        descriptionAr: 'نبات زاحف صحراوي، أزهاره صفراء تجذب النحل.',
        heightMinMeters: 0.1,
        heightMaxMeters: 0.3,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 4, endMonth: 8, peakMonth: 6, flowerColor: 'أصفر', nectarTiming: 'MORNING' },
        environment: { climate: ['ARID', 'HYPER_ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Malva parviflora',
        commonNameAr: 'الخبيز',
        commonNameEn: 'Little mallow',
        localNames: ['الخبيز', 'الخبازة'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Malvaceae',
        descriptionAr: 'نبات عشبي شتوي ربيعي، ينتشر في الأراضي الزراعية.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 2, endMonth: 5, peakMonth: 3, flowerColor: 'أبيض وردي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Matricaria chamomilla',
        commonNameAr: 'البابونج',
        commonNameEn: 'Chamomile',
        localNames: ['البابونج', 'الكاموميل'],
        synonyms: ['Chamomilla recutita'],
        plantType: 'HERB',
        family: 'Asteraceae',
        descriptionAr: 'نبات عطري طبي، أزهاره تجذب النحل.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض مع أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['MEDITERRANEAN', 'SEMI_ARID'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة الجوف', 'منطقة تبوك'],
        cultivatedRegions: ['منطقة الجوف', 'منطقة تبوك'],
    },
    {
        scientificName: 'Asphodelus spp.',
        commonNameAr: 'البروق',
        commonNameEn: 'Asphodel',
        localNames: ['البروق'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Asphodelaceae',
        descriptionAr: 'نبات عشبي ربيعي، أزهاره جميلة لكن قيمة نحلية منخفضة.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 2, endMonth: 5, peakMonth: 3, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Mentha spp.',
        commonNameAr: 'النعناع',
        commonNameEn: 'Mint',
        localNames: ['النعناع', 'النعنع'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Lamiaceae',
        descriptionAr: 'نبات عطري، يزرع في الحدائق، أزهاره تجذب النحل.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 5, endMonth: 8, peakMonth: 6, flowerColor: 'بنفسجي فاتح', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN', 'TROPICAL'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'PARTIAL_SHADE' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Coriandrum sativum',
        commonNameAr: 'الكزبرة',
        commonNameEn: 'Coriander / Cilantro',
        localNames: ['الكزبرة', 'القزبرة', 'الكسبرة'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Apiaceae',
        descriptionAr: 'نبات عطري يزرع كتوابل، أزهاره تجذب النحل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 0.8,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة القصيم', 'منطقة الرياض', 'منطقة عسير', 'منطقة جازان'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Eruca sativa',
        commonNameAr: 'الجرجير',
        commonNameEn: 'Rocket / Arugula',
        localNames: ['الجرجير'],
        synonyms: ['Eruca vesicaria'],
        plantType: 'HERB',
        family: 'Brassicaceae',
        descriptionAr: 'نبات عشبي سريع النمو، أزهاره تجذب النحل.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 2, endMonth: 4, peakMonth: 3, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة القصيم', 'منطقة الرياض', 'منطقة الجوف', 'منطقة تبوك'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Anthemis spp.',
        commonNameAr: 'الأقحوان البري',
        commonNameEn: 'Wild chamomile',
        localNames: ['الأقحوان', 'البابونج البري'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Asteraceae',
        descriptionAr: 'نبات عشبي ربيعي، أزهاره تشبه البابونج.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.5,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 4, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة الرياض', 'منطقة القصيم', 'منطقة حائل', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Medicago sativa',
        commonNameAr: 'البرسيم الحجازي',
        commonNameEn: 'Alfalfa / Lucerne',
        localNames: ['البرسيم', 'الحجازي', 'الفصة'],
        synonyms: [],
        plantType: 'HERB',
        family: 'Fabaceae',
        descriptionAr: 'غزير الرحيق، مصدر رئيسي في المزارع، ينتج عسلاً فاتح اللون.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 5 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH', notes: 'غزير الرحيق — مصدر رئيسي في المزارع' },
        flowering: { startMonth: 5, endMonth: 10, peakMonth: 7, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },

    // ===== المحاصيل الزراعية (Crops) =====
    {
        scientificName: 'Medicago sativa',
        commonNameAr: 'البرسيم (الجت)',
        commonNameEn: 'Alfalfa',
        localNames: ['البرسيم', 'الجت', 'الفصة'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Fabaceae',
        descriptionAr: 'محصول علفي هام، غزير الرحيق وحبوب اللقاح، مصدر رئيسي للعسل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 5 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 5, endMonth: 10, peakMonth: 7, flowerColor: 'بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جنوب غرب آسيا (مستورد)'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Helianthus annuus',
        commonNameAr: 'دوار الشمس',
        commonNameEn: 'Sunflower',
        localNames: ['دوار الشمس', 'عباد الشمس'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Asteraceae',
        descriptionAr: 'محصول رحيقي هام، أزهاره كبيرة تجذب أعداداً كبيرة من النحل.',
        heightMinMeters: 1,
        heightMaxMeters: 3,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH', notes: 'محصول رحيقي هام' },
        flowering: { startMonth: 4, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['أمريكا الشمالية (مستورد)'],
        cultivatedRegions: ['منطقة القصيم', 'منطقة الرياض', 'منطقة حائل', 'منطقة الجوف', 'منطقة تبوك'],
    },
    {
        scientificName: 'Cucurbitaceae',
        commonNameAr: 'القرعيات (القرع، الخيار، البطيخ)',
        commonNameEn: 'Cucurbits',
        localNames: ['القرع', 'الخيار', 'البطيخ', 'الكنتالوب'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Cucurbitaceae',
        descriptionAr: 'مجموعة من المحاصيل الزراعية الصيفية، أزهارها تجذب النحل.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.5,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 4, endMonth: 8, peakMonth: 6, flowerColor: 'أصفر', nectarTiming: 'MORNING' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['LOAMY', 'SANDY', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Allium spp.',
        commonNameAr: 'الكراث (البصل، الثوم)',
        commonNameEn: 'Onion / Garlic / Leek',
        localNames: ['البصل', 'الثوم', 'الكراث'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Amaryllidaceae',
        descriptionAr: 'محاصيل بصلية، أزهارها كروية تجذب النحل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1.2,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض بنفسجي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Peganum harmala',
        commonNameAr: 'الحرمل',
        commonNameEn: 'Harmal / Syrian rue',
        localNames: ['الحرمل'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Zygophyllaceae',
        descriptionAr: 'نبات معمر، أزهاره تجذب النحل لكن قيمة نحلية منخفضة.',
        heightMinMeters: 0.3,
        heightMaxMeters: 0.8,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 5, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY', 'SALINE'], waterNeeds: 'VERY_LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Trifolium spp.',
        commonNameAr: 'البرسيم المصري (البرسيم)',
        commonNameEn: 'Clover',
        localNames: ['البرسيم', 'النفل', 'البرسيم المصري'],
        synonyms: ['Trifolium alexandrinum'],
        plantType: 'CROP',
        family: 'Fabaceae',
        descriptionAr: 'محصول علفي شتوي ربيعي، غزير الرحيق.',
        heightMinMeters: 0.3,
        heightMaxMeters: 0.8,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'HIGH', rating: 4 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 2, endMonth: 5, peakMonth: 4, flowerColor: 'أبيض وردي', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'HIGH', sunExposure: 'FULL_SUN' },
        nativeRegions: ['اليمن (مستورد)'],
        cultivatedRegions: ['منطقة القصيم', 'منطقة الرياض', 'منطقة حائل', 'منطقة الجوف'],
    },
    {
        scientificName: 'Brassica napus',
        commonNameAr: 'بذرة اللفت (السلجم)',
        commonNameEn: 'Rapeseed / Canola',
        localNames: ['السلجم', 'بذرة اللفت', 'الكانولا'],
        synonyms: [],
        plantType: 'CROP',
        family: 'Brassicaceae',
        descriptionAr: 'محصول زيتي هام، أزهاره صفراء غزيرة تجذب أعداداً كبيرة من النحل.',
        heightMinMeters: 0.5,
        heightMaxMeters: 1.5,
        beekeepingValue: { nectar: { production: 'HIGH', rating: 4 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'HIGH' },
        flowering: { startMonth: 2, endMonth: 4, peakMonth: 3, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['MEDITERRANEAN', 'SEMI_ARID'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['أوروبا (مستورد)'],
        cultivatedRegions: ['منطقة الجوف', 'منطقة تبوك', 'منطقة حائل', 'منطقة القصيم'],
    },

    // ===== أزهار الربيع البرية (Wildflowers) =====
    {
        scientificName: 'Spring wildflowers mix',
        commonNameAr: 'زهور الربيع (متنوعة)',
        commonNameEn: 'Spring wildflowers',
        localNames: ['زهور الربيع', 'الربيعية'],
        synonyms: [],
        plantType: 'WILDFLOWER',
        descriptionAr: 'مجموعة متنوعة من زهور الربيع البرية، مصدر غذائي مهم للنحل في بداية الموسم.',
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 3 }, pollen: { production: 'MEDIUM', rating: 3 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 2, endMonth: 5, peakMonth: 3, flowerColor: 'متنوع', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Ranunculus spp.',
        commonNameAr: 'الحوذان البري',
        commonNameEn: 'Buttercup',
        localNames: ['الحوذان', 'كأس المروج'],
        synonyms: [],
        plantType: 'WILDFLOWER',
        family: 'Ranunculaceae',
        descriptionAr: 'نبات عشبي ربيعي، أزهاره صفراء لامعة تجذب النحل.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.6,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 2, endMonth: 5, peakMonth: 3, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'CLAY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Ammi majus',
        commonNameAr: 'الخلة (البسفاج)',
        commonNameEn: 'Bishop\'s flower / Queen Anne\'s lace',
        localNames: ['الخلة', 'البسفاج'],
        synonyms: [],
        plantType: 'WILDFLOWER',
        family: 'Apiaceae',
        descriptionAr: 'نبات عشبي بري، أزهاره بيضاء مظلية تجذب النحل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 4, endMonth: 6, peakMonth: 5, flowerColor: 'أبيض', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة جازان'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Senna spp.',
        commonNameAr: 'السنا العشرق',
        commonNameEn: 'Senna',
        localNames: ['العشرق', 'السنا'],
        synonyms: [],
        plantType: 'WILDFLOWER',
        family: 'Fabaceae',
        descriptionAr: 'نبات بري، أزهاره تجذب النحل في الربيع والصيف.',
        heightMinMeters: 0.5,
        heightMaxMeters: 1.5,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 7, peakMonth: 5, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'TROPICAL'], soilType: ['SANDY', 'LOAMY'], waterNeeds: 'LOW', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة جازان', 'منطقة نجران', 'منطقة مكة المكرمة'],
        cultivatedRegions: [],
    },
    {
        scientificName: 'Anethum graveolens',
        commonNameAr: 'الشبت',
        commonNameEn: 'Dill',
        localNames: ['الشبت', 'القدونس', 'العجور'],
        synonyms: ['Peucedanum graveolens'],
        plantType: 'WILDFLOWER',
        family: 'Apiaceae',
        descriptionAr: 'نبات عطري، أزهاره مظلية تجذب النحل.',
        heightMinMeters: 0.3,
        heightMaxMeters: 1,
        beekeepingValue: { nectar: { production: 'MEDIUM', rating: 2 }, pollen: { production: 'MEDIUM', rating: 2 }, honeydew: false, attraction: 'MEDIUM' },
        flowering: { startMonth: 3, endMonth: 6, peakMonth: 5, flowerColor: 'أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['ARID', 'SEMI_ARID', 'MEDITERRANEAN'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['جميع مناطق المملكة'],
        cultivatedRegions: ['جميع مناطق المملكة'],
    },
    {
        scientificName: 'Narcissus spp.',
        commonNameAr: 'النرجس البري',
        commonNameEn: 'Wild narcissus',
        localNames: ['النرجس', 'العبهار'],
        synonyms: [],
        plantType: 'WILDFLOWER',
        family: 'Amaryllidaceae',
        descriptionAr: 'نبات بصلي شتوي، أزهاره عطرة لكن قيمة نحلية منخفضة.',
        heightMinMeters: 0.2,
        heightMaxMeters: 0.5,
        beekeepingValue: { nectar: { production: 'LOW', rating: 1 }, pollen: { production: 'LOW', rating: 1 }, honeydew: false, attraction: 'LOW' },
        flowering: { startMonth: 1, endMonth: 4, peakMonth: 2, flowerColor: 'أبيض أصفر', nectarTiming: 'ALL_DAY' },
        environment: { climate: ['MEDITERRANEAN', 'SEMI_ARID'], soilType: ['LOAMY', 'SANDY'], waterNeeds: 'MEDIUM', sunExposure: 'FULL_SUN' },
        nativeRegions: ['منطقة عسير', 'منطقة الباحة', 'منطقة تبوك', 'منطقة الجوف'],
        cultivatedRegions: [],
    },
];

async function seedPlants() {
    console.log('🌱 بدء بذر بيانات مكتبة النباتات...');
    console.log(`📦 العدد الإجمالي: ${plants.length} نبتة`);

    let created = 0;
    let skipped = 0;

    for (const plant of plants) {
        const existing = await prisma.plantLibrary.findUnique({
            where: { scientificName: plant.scientificName },
        });

        if (existing) {
            console.log(`⏭️  موجود بالفعل: ${plant.commonNameAr}`);
            skipped++;
            continue;
        }

        await prisma.plantLibrary.create({
            data: {
                scientificName: plant.scientificName,
                commonNameAr: plant.commonNameAr,
                commonNameEn: plant.commonNameEn,
                localNames: plant.localNames,
                synonyms: plant.synonyms,
                plantType: plant.plantType,
                family: plant.family,
                descriptionAr: plant.descriptionAr,
                heightMinMeters: plant.heightMinMeters,
                heightMaxMeters: plant.heightMaxMeters,
                beekeepingValue: plant.beekeepingValue,
                flowering: plant.flowering,
                environment: plant.environment,
                nativeRegions: plant.nativeRegions,
                cultivatedRegions: plant.cultivatedRegions,
                images: [],
                videos: [],
                references: null,
                verified: false,
            },
        });

        console.log(`✅ تم الإضافة: ${plant.commonNameAr} (${plant.scientificName})`);
        created++;
    }

    console.log(`\n🎉 تم الانتهاء من بذر بيانات النباتات!`);
    console.log(`   - تمت الإضافة: ${created}`);
    console.log(`   - تم التخطي (موجود مسبقاً): ${skipped}`);
}

seedPlants()
    .catch((e) => {
        console.error('❌ خطأ أثناء البذر:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
